//
// This code was generated by a tool.  Do not modify.
//

#import <Foundation/Foundation.h>
#import "DtoType.h"

#ifndef ObservationListDto_h
#define ObservationListDto_h
@interface ObservationListDto: NSObject<DtoType>

@property NSString* code;
@property NSString* desc;
@property NSNumber* maxValueLength;
@property NSNumber* isRestricted;
@property NSNumber* selectionType;
@property NSString* multiSelectSeparator;
@property NSString* controlType;
@property NSNumber* isHorizontal;
@property NSMutableArray* listItems;

- (instancetype) initWithBondObject: (void*)obj;
- (instancetype) initWithJson: (NSString*)json;
- (instancetype) initWithJsonDictionary: (NSDictionary*)dictionary;
- (instancetype) initWithByteArray: (uint8_t*)byteArray length:(uint32_t)len;
- (void*) toBondObject;
- (const uint8_t*) toByteArray: (uint32_t*)resultLen;

@end

#endif
