//
// This code was generated by a tool.  Do not modify.
//

#import <Foundation/Foundation.h>
#import "DtoType.h"
#import "ObservationListDto.h"
#import "BaseEntityDto.h"

#ifndef ObservationDescriptionDto_h
#define ObservationDescriptionDto_h
@interface ObservationDescriptionDto: BaseEntityDto<DtoType>

@property NSString* kindStringValue;
@property NSNumber* kind;
@property NSMutableArray* ranges;
@property ObservationListDto* obsList;
@property NSString* name;
@property NSString* desc;
@property NSDate* effectiveDate;
@property NSDate* expiryDate;
@property NSNumber* isGenericItem;
@property NSNumber* isClientCharacteristic;
@property NSString* physicalNoteType;
@property NSNumber* isOutcome;
@property NSString* dataType;
@property NSString* calculationType;
@property NSString* fluidBalanceType;
@property NSString* summaryType;
@property NSString* cumulativeStartOfDayType;
@property NSNumber* calculateCumulative;
@property NSString* i0Subtype;
@property NSNumber* includeInTotals;
@property NSNumber* allowApproximates;
@property NSNumber* showAbsoluteValues;
@property NSString* unitOfMeasure;
@property NSNumber* numDecimalsIn;
@property NSNumber* numDecimalsOut;
@property NSNumber* useNumericSeparator;
@property NSNumber* maximumLength;
@property NSNumber* numberOfLines;
@property NSNumber* isMultiSelect;
@property NSString* valueSeparator;
@property NSString* textValidationDict;
@property NSNumber* hasNumericEquiv;
@property NSString* trueText;
@property NSString* falseText;
@property NSNumber* displayUOM;
@property NSString* modifyFormFilter;
@property NSNumber* isDeviceInterface;
@property NSString* parameterType;
@property NSNumber* roundOffResult;
@property NSNumber* outputNumDecimalsIn;
@property NSNumber* outputNumDecimalsOut;
@property NSNumber* rateNumDecimalsIn;
@property NSNumber* rateNumDecimalsOut;
@property NSNumber* doseNumDecimalsIn;
@property NSNumber* doseNumDecimalsOut;
@property NSNumber* enterDetailDialog;
@property NSString* userDictionaryCode;
@property NSString* formula;
@property NSString* calculationHeading;
@property NSString* maskingFormat;
@property NSNumber* isHorizontal;
@property NSString* rightJustifiedLabel;
@property NSString* rightJustifiedLabelFontSize;
@property NSString* leftJustifiedLabel;
@property NSString* leftJustifiedLabelFontSize;
@property NSString* commentFontSize;
@property NSString* modifyFormFilterFontSize;
@property NSString* fontSize;
@property NSString* componentFontSize;
@property NSNumber* enterIntake;
@property NSNumber* enterOutput;
@property NSNumber* enterNet;
@property NSNumber* enter24Hr;
@property NSString* labelIn;
@property NSString* labelOut;
@property NSString* labelNet;
@property NSString* label24Hr;
@property NSString* totalVolume;
@property NSString* totalVolumeUnit;
@property NSString* rate;
@property NSString* rateUnit;
@property NSNumber* noEditing;
@property NSNumber* hasModifier;
@property NSNumber* isLocked;
@property NSNumber* hasWDL;
@property NSString* siteFontSize;
@property NSString* siteDeviceFontSize;
@property NSNumber* isRTFInput;

- (instancetype) initWithBondObject: (void*)obj;
- (instancetype) initWithJson: (NSString*)json;
- (instancetype) initWithJsonDictionary: (NSDictionary*)dictionary;
- (instancetype) initWithByteArray: (uint8_t*)byteArray length:(uint32_t)len;
- (void*) toBondObject;
- (const uint8_t*) toByteArray: (uint32_t*)resultLen;

@end

#endif
