//
// This code was generated by a tool.  Do not modify.
//

#import <Foundation/Foundation.h>
#import "DtoType.h"

#ifndef TelephoneNumberDto_h
#define TelephoneNumberDto_h
@interface TelephoneNumberDto: NSObject<DtoType>

@property NSNumber* countryCode;
@property NSString* number;
@property NSString* ext;
@property NSString* kindStringValue;
@property NSNumber* kind;

- (instancetype) initWithBondObject: (void*)obj;
- (instancetype) initWithJson: (NSString*)json;
- (instancetype) initWithJsonDictionary: (NSDictionary*)dictionary;
- (instancetype) initWithByteArray: (uint8_t*)byteArray length:(uint32_t)len;
- (void*) toBondObject;
- (const uint8_t*) toByteArray: (uint32_t*)resultLen;

@end

#endif
